const expres = require("express")
const multer = require("multer")
const fs = require("fs")
const path = require("path")
const pdfparse = require("pdf-parse")
const pdfDocumente = require("pdfkit")
const router = expres.Router()
const upload = multer({dest:"uploads/"})